### ISSUE TITLE
Alternative for doiuse?

### ISSUE THREAD

**Issue by sidx1024** [ismay/stylelint-no-unsupported-browser-features#267]
I see that [doiuse](https://github.com/anandthakker/doiuse) (https://github.com/anandthakker/doiuse/issues/110) is no longer maintained (since 2021). Do we plan to have an alternative?

**Comment by anandthakker** [comment]
I'd be happy to transfer ownership of doiuse. @ismay as the owner of this related project, do you want it?

**Comment by ismay** [comment]
> I'd be happy to transfer ownership of doiuse. @ismay as the owner of this related project, do you want it?

Hi @anandthakker, thanks for the offer! That does sound interesting. I was wondering, what do you think doiuse needs at this stage? Does it just need some care and maintenance, or would you overhaul certain parts? Wondering what your perspective is on the needs of the lib at this stage.

**Comment by ismay** [comment]
> I've forked it a couple of months ago and did a bit of a rewrite. I don't actively maintain it, but it's a bit further along:
> 
> https://github.com/clshortfuse/doiuse2

Anything that would be worth contributing back to doiuse? Or was it more just exploration?

**Comment by clshortfuse** [comment]
I think I originally forked it because I write in only ESM and couldn't import `doiuse`. 

* Rewrite everything as ESM
* Export Class for default exports
* Fold in `anandthakker/css-rule-stream`
* Drop babel
* Drop Node 10
* Use `rollup` for CommonJS support
* Use `tap` instead of `tape` for testing
* Create one test file per feature (instead of all in one file)
* Add `coverage` tests
* Enforced type checking via `jsconfig.json`.
* Generate `types` folder on publish

The rewrite makes it a bit harder to do a direct comparison against upstream. Things meant to be exported are in `/lib` where as internal utilities are in `/utils`.

I don't think I broke any APIs, but there wasn't an API test. The `/exports` is meant to replicate CommonJS imports. One for the default export as a function (`doiuse()`) and one for `doiuse/stream`.

I also forked this repository, but that's just to change one line (import `doiuse2` instead of `doiuse`) and it seems to work fine. It definitely benefit from some extra tests.

**Comment by clshortfuse** [comment]
It seems the last (internal) state of the library adding `@mdn/browser-compat-data` support to double check feature support.

**Comment by ismay** [comment]
@clshortfuse Sounds like you've done quite a bit of work on it. Thanks for the explanation 🙏

@anandthakker To be honest, after thinking about it I'm not sure if I have the time to properly maintain doiuse. I'd like to, and I've thought about it in the past. But I think if I'm honest with myself I probably just don't have the time to give it the attention it deserves.

I'm not sure if this fits both of your goals @clshortfuse & @anandthakker, but would you be interested in the job @clshortfuse? It depends on whether this works for @anandthakker of course, I can't speak on his behalf.

**Comment by anandthakker** [comment]
I'd be happy to transfer owneship to @clshortfuse if you want it

**Comment by clshortfuse** [comment]
Sorry, I lost track of the discussion!

@anandthakker I'm not sure what that entails. Are we talking github or npm? Regardless, I'm fine with continuing maintenance on `doiuse`.

**Comment by ismay** [comment]
Hey @anandthakker I was wondering how it's going with adding @clshortfuse as a doiuse maintainer? I believe this is his npm account: https://www.npmjs.com/~shortfuse (correct me if I'm wrong @clshortfuse).

I think both github and npm rights would be useful to have for him.

**Comment by clshortfuse** [comment]
@ismay 6.0.0 is out.

I've switched my projects back to this repo with an override in `package.json`

````json
"overrides": {
  "stylelint-no-unsupported-browser-features": {
    "doiuse": "^6.0.0"
  }
},
````

So far, all is good, but you might want to double-check. 😄 It's supposed to be backwards compatible with the exception of dropping support for EOL Node versions.

**Comment by ismay** [comment]
> @ismay 6.0.0 is out.
> 
> I've switched my projects back to this repo with an override in `package.json`
> 
> ```json
> "overrides": {
>   "stylelint-no-unsupported-browser-features": {
>     "doiuse": "^6.0.0"
>   }
> },
> ```
> 
> So far, all is good, but you might want to double-check. 😄 It's supposed to be backwards compatible with the exception of dropping support for EOL Node versions.

@clshortfuse Thanks for the heads up! I've got a PR here for the update to doiuse 6: https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/277, but I'm getting a linting error that makes me suspect there's an issue with doiuse 6's commonjs export. See here: https://github.com/ismay/stylelint-no-unsupported-browser-features/actions/runs/5456893877/jobs/9930302119?pr=277. We can continue the chat in the PR, let me know what you think. On master of this repo module resolution works fine, so I'm _suspecting_ it's the update to doiuse.
