### ISSUE TITLE
is working of "ignorePartialSupport: false" correct?

### ISSUE THREAD

**Issue by cakkypamucm** [ismay/stylelint-no-unsupported-browser-features#270]
- I have stylelintrc config:
```
{
  "plugins": [
    "stylelint-no-unsupported-browser-features"
  ],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {
      "severity": "warning",
      "ignorePartialSupport": false
    }]
  }
}
```
and browserslistrc config:
```
> 1%
last 2 versions and not dead
not op_mini all
```
As you can [see](https://browsersl.ist/#q=%3E+1%25%2Clast+2+versions+and+not+dead%2Cnot+op_mini+all), there is `Samsung Internet` browser in the list  

- I execute `stylelint --fix` and among checking files there is a one with line
`height: 100dvh;`
As you can [see](https://caniuse.com/?search=dvh), `Samsung Internet` is not supported `dvh`

- I expect warning about `Samsung Internet` and `dvh` (because of `ignorePartialSupport`: **false**) - but there is no warning :confused:

- I [updated](https://github.com/browserslist/browserslist#update-caniuse-lite) caniuse and try to passing browsers directly:
```
"plugin/no-unsupported-browser-features": [true, {
      "browsers": ["> 1%", "last 2 versions and not dead", "not op_mini all"], // passing browsers directly
      "severity": "warning", 
      "ignorePartialSupport": false
    }]
```
but there is still no warning :confused:

- So my question is:
how can I get warning about `Samsung Internet` and `dvh` using `ignorePartialSupport`?

_Maybe related with [this PR](https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/231)_

**Comment by ismay** [comment]
To answer the question:

> is working of "ignorePartialSupport: false" correct?

yes, it should be correct. It's tested here: https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/lib/index.test.js#L170-L261. If you want partialSupport to be set to false you don't need to pass it explicitly, `false` is the default. For your issue I think partial support is not important anyway because I don't see partial support mentioned on the caniuse section for dvh.

There are a number of things that could be affecting your setup and I can't debug that at a distance. If you feel that something this library is doing is incorrect then please submit a failing test as a PR that demonstrates the bug.

For more QA style help you can open a discussion. I'll close this since there's not yet anything actionable for me here.
